[pytest]

markers =
    smoke: smoke test cases
    regression: regression test cases
    positive: positive test scenarios
    negative: negative test scenarios
    e2e: end-to-end user journey test
    order: execution order marker

addopts = --alluredir=./reports/allure-results --clean-alluredir